### ISSUE TITLE
Projeyi cihan'a aktarip private repository haline getirilmesi.

### ISSUE THREAD

**Issue by cihanozcelik** [ehidna/uyelikSistemi#14]
pagerhino.com bir startup'a dönüşeceği için private bir repo üzerinde geliştirmemiz daha mantıklı olacaktır. reponu bana aktarırsan bende private'a çeviririm.

**Comment by ehidna** [comment]
Ben private'a cevirdim 1 tane kullanma hakkim var.

**Comment by cihanozcelik** [comment]
Tamamdir.
